name: Build plugins artifacts
on: [pull_request, workflow_call]

env:
  # Link for Linux zip file from https://developer.android.com/studio/archive
  ANDROID_STUDIO_URL: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.3.2.1/android-studio-2023.3.2.1-linux.tar.gz
  COMPILER_VERSION: 233.14475.28

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Download Android Studio
        run: |
          wget -O android-studio.tar.gz -q $ANDROID_STUDIO_URL
          tar -xf android-studio.tar.gz -C ./
      - name: Build plugins
        run: |
          ./gradlew buildAllPlugins \
            -DandroidStudioPath="$(pwd)/android-studio" \
            -DandroidStudioCompilerVersion="$COMPILER_VERSION" \
            -DandroidStudioPluginsNames="org.jetbrains.android,org.jetbrains.kotlin,com.intellij.java,org.intellij.groovy,Git4Idea,org.intellij.intelliLang"
